name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Adjust if needed

      - name: Install dependencies
        run: npm install

      - name: Build Angular application
        run: npm run build --prod
        env:
          CI: true  # Ensures non-interactive mode for Angular

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
        name: angular-build
        path: dist/[actual-project-name]  # Replace with the actual folder name in the dist directory


  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: angular-build

      - name: Log in to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com

      - name: Build and tag Docker image
        run: |
          docker build -t angular-app-image .
          VERSION_TAG="1.0.${{ github.run_id }}-${{ github.ref_name }}"
          DOCKER_IMAGE="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:$VERSION_TAG"
          docker tag angular-app-image:latest $DOCKER_IMAGE

      - name: Push Docker image to ECR
        run: |
          docker push $DOCKER_IMAGE

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: SSH and Deploy on EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          echo "${{ secrets.EC2_KEY }}" > /tmp/ssh_key.pem
          chmod 600 /tmp/ssh_key.pem
          
          REMOTE_COMMAND="
            $(aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com) &&
            docker pull $DOCKER_IMAGE &&
            docker stop demo-twelve || true &&
            docker container rm -f demo-twelve || true &&
            docker run -d --name demo-twelve -p 8080:8080 $DOCKER_IMAGE
          "

          ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST_DEV }} "$REMOTE_COMMAND"
